# Generated by Django 4.2 on 2024-12-06 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(choices=[('bitcoin', 'Bitcoin'), ('ethereum', 'Ethereum'), ('tether', 'Tether'), ('binancecoin', 'Binancecoin'), ('xrp', 'Xrp'), ('cardano', 'Cardano'), ('dogecoin', 'Dogecoin'), ('solana', 'Solana'), ('tron', 'Tron'), ('polkadot', 'Polkadot'), ('polygon', 'Polygon'), ('litecoin', 'Litecoin'), ('shiba', 'Shiba'), ('dai', 'Dai'), ('avalanche', 'Avalanche'), ('wrappedbitcoin', 'Wrappedbitcoin'), ('uniswap', 'Uniswap'), ('chainlink', 'Chainlink'), ('leo', 'Leo'), ('stellar', 'Stellar')], max_length=50)),
                ('quantity', models.FloatField()),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='alerts.portfolio')),
            ],
        ),
    ]
