# Generated by Django 4.2 on 2024-12-06 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_portfolio_holding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='user',
        ),
        migrations.DeleteModel(
            name='Holding',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
